In [3]:
%matplotlib inline
import cv2
import numpy as np
from matplotlib import pyplot as plt

Image_a: IMG_20200111_141756.jpg
Image_b: high_spat_freq.bmp
1. Calculate the power of the original image a, which will be denoted as Pa.
2. Apply the vertical edge detector filter hVED to image a and compute the power of
the resulting filtered image, denoted as Phpa.
3. Filter image a with the Gaussian filter hGLP (from Question 2). Next, apply the
vertical edge detector filter hVED to the filtered image and compute the power of the
resulting image, Plphpa.
4. Filter image a with the Gaussian filter hGLP (from Question 2) twice. Next, apply the
vertical edge detector filter hVED to the twice‐filtered image and compute the power
of the resulting image, Plplphpa.
5. Open a new image named high_spat_freq.bmp and label it as b.
6. Repeat the entire process outlined above for image b. Calculating Pb, Phpb, Plphpb,
and Plplphpb.

In [6]:
#utils_2023 functions

# function to compute the image power. input could be graylevel or color. 
#
def am_power(a):
    dim1 = a.shape
    
    if len(dim1)==2:
        sz = dim1[0] * dim1[1] 
    elif len(dim1)==3:
        sz = dim1[0] * dim1[1] * dim1[2]        
    pa = np.sum( a ** 2.0) / sz    
    
    return pa

gausslp = 1/273 * np.array([[1, 4, 7, 4, 1], [4, 16, 26, 16, 4], [7, 26, 41, 26, 7], [4, 16, 26, 16, 4], [1, 4, 7, 4, 1]])
print(gausslp)

h_ved = np.array([[-1, 0, 1], [-2, 0, 2], [-1, 0, 1]])
print(h_ved)

[[0.003663   0.01465201 0.02564103 0.01465201 0.003663  ]
 [0.01465201 0.05860806 0.0952381  0.05860806 0.01465201]
 [0.02564103 0.0952381  0.15018315 0.0952381  0.02564103]
 [0.01465201 0.05860806 0.0952381  0.05860806 0.01465201]
 [0.003663   0.01465201 0.02564103 0.01465201 0.003663  ]]
[[-1  0  1]
 [-2  0  2]
 [-1  0  1]]


In [7]:
# Cell for IMG_20200111_141756.jpg, high_spat_freq.bmp
im_file_1 = '../CS4243_2023_images_small/IMG_20200111_141756.jpg'
img1 = cv2.imread(im_file_1)
# plt.imshow(img1)

power_a = am_power(img1)

filtered_once_a = cv2.filter2D(img1, ddepth = -1, kernel = h_ved)
power_hpa = am_power(filtered_once_a)

filtered_twice_a = cv2.filter2D(img1, ddepth = -1, kernel = gausslp)
filtered_twice_a = cv2.filter2D(filtered_twice_a, ddepth = -1, kernel = h_ved)
power_lphpa = am_power(filtered_twice_a)

filtered_thrice_a = cv2.filter2D(img1, ddepth = -1, kernel = gausslp)
filtered_thrice_a = cv2.filter2D(filtered_thrice_a, ddepth = -1, kernel = gausslp)
filtered_thrice_a = cv2.filter2D(filtered_thrice_a, ddepth = -1, kernel = h_ved)
power_lplphpa = am_power(filtered_thrice_a)

print("Pa =", power_a)
print("Phpa =", power_hpa)
print("Plphpa =", power_lphpa)
print("Plplphpa =", power_lplphpa)
print("Ratio of Plplphpa / Phpa =", power_lplphpa / power_hpa)
print("Ratio of Plplphpa / Pa =", power_lplphpa / power_a)
print("------------------------------------------------------")


im_file_2 = '../CS4243_2023_images_small/high_spat_freq.bmp'
img2 = cv2.imread(im_file_2)
# plt.imshow(img1)

power_b = am_power(img2)

filtered_once_b = cv2.filter2D(img2, ddepth = -1, kernel = h_ved)
power_hpb = am_power(filtered_once_b)

filtered_twice_b = cv2.filter2D(img2, ddepth = -1, kernel = gausslp)
filtered_twice_b = cv2.filter2D(filtered_twice_b, ddepth = -1, kernel = h_ved)
power_lphpb = am_power(filtered_twice_b)

filtered_thrice_b = cv2.filter2D(img2, ddepth = -1, kernel = gausslp)
filtered_thrice_b = cv2.filter2D(filtered_thrice_b, ddepth = -1, kernel = gausslp)
filtered_thrice_b = cv2.filter2D(filtered_thrice_b, ddepth = -1, kernel = h_ved)
power_lplphpb = am_power(filtered_thrice_b)

print("Pb =", power_b)
print("Phpb =", power_hpb)
print("Plphpb =", power_lphpb)
print("Plplphpb =", power_lplphpb)
print("Ratio of Plplphpb / Phpb =", power_lplphpb / power_hpb)
print("Ratio of Plplphpb / Pb =", power_lplphpb / power_b)


Pa = 17178.74590714809
Phpa = 938.5970504717069
Plphpa = 436.2485838613087
Plplphpa = 273.8928085718901
Ratio of Plplphpa / Phpa = 0.29181085582384997
Ratio of Plplphpa / Pa = 0.015943702180141277
------------------------------------------------------
Pb = 37922.38235473633
Phpb = 24450.582790374756
Plphpb = 8343.05661392212
Plplphpb = 3231.2771224975586
Ratio of Plplphpb / Phpb = 0.13215542345966438
Ratio of Plplphpb / Pb = 0.08520765104553056


Conclusion: Answer (c) in Canvas